Repository replicatedhq/helm-charts, pull requests merged in 2023-04, with the labels that each got.

#19 Replicated Library Chart v0.3.0
  .gitignore
  charts/replicated-library/BREAK_GLASS.md
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README.md.gotmpl
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/README_CONFIG.md.gotmpl
  charts/replicated-library/templates/lib/_container.tpl
  charts/replicated-library/values.yaml
Labels: bug::normal, type::bug

#21 Remove some extra spaces in container and pod templates
  charts/replicated-library/templates/lib/_container.tpl
  charts/replicated-library/templates/lib/_pod.tpl
Labels: type::chore

#24 Default liveness and readiness probes if not defined
  charts/replicated-library/templates/lib/_container.tpl
Labels: type::feature

#25 Update version to 0.4.0
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
Labels: type::docs, type::chore

#29 Document Advanced Templating
  charts/replicated-library/ADVANCED_TEMPLATING.md
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README.md.gotmpl
Labels: type::chore

#28 Dynamic object names per release
  charts/replicated-library/README.md
  charts/replicated-library/templates/_all.tpl
  charts/replicated-library/templates/classes/_configmap.tpl
  charts/replicated-library/templates/classes/_ingress.tpl
  charts/replicated-library/templates/classes/_pvc.tpl
  charts/replicated-library/templates/classes/_secret.tpl
  charts/replicated-library/templates/classes/_service.tpl
  charts/replicated-library/templates/lib/_configmap.tpl
  charts/replicated-library/templates/lib/_container.tpl
  charts/replicated-library/templates/lib/_deployment.tpl
  charts/replicated-library/templates/lib/_ingress.tpl
  charts/replicated-library/templates/lib/_labels.tpl
  charts/replicated-library/templates/lib/_names.tpl
  charts/replicated-library/templates/lib/_pod.tpl
  charts/replicated-library/templates/lib/_pod_annotations.tpl
  charts/replicated-library/templates/lib/_probes.tpl
  charts/replicated-library/templates/lib/_pvc.tpl
  charts/replicated-library/templates/lib/_secret.tpl
  charts/replicated-library/templates/lib/_service.tpl
  charts/replicated-library/templates/lib/_serviceaccount.tpl
  charts/replicated-library/values.yaml
Labels: type::chore

#32 Make release 0.5.0
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
Labels: type::chore

#35 spelling error in _pod_annotations.tpl, line 21 - replicated-library.configmap --> replicated-library.configmaps
  charts/replicated-library/templates/lib/_pod_annotations.tpl
Labels: bug::normal, type::bug

#34 Add release to selectors
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_labels.tpl
  charts/replicated-library/templates/lib/_names.tpl
Labels: bug::normal, type::bug

#39 Davidr add type option for secrets
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/classes/_secret.tpl
  charts/replicated-library/values.yaml
Labels: type::feature

#33 Automatically add prefix to persistent volumes
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_pod.tpl
  charts/replicated-library/values.yaml
Labels: type::feature

#40 Add statefulsets
  charts/replicated-library/templates/lib/_names.tpl
  charts/replicated-library/templates/lib/_statefulset.tpl
  charts/replicated-library/values.yaml
Labels: type::feature

#41 Release 0.6.0
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
Labels: type::chore

#42 [wg-easy]
  charts/wg-easy/.helmignore
  charts/wg-easy/Chart.lock
  charts/wg-easy/Chart.yaml
  charts/wg-easy/templates/replicated-library.yaml
  charts/wg-easy/values.yaml
Labels: type::feature

#43 Add dependencies for chart releases
  .github/workflows/publish.yaml
Labels: bug::normal, type::bug

#44 Fix automatic prefix on volume mounts
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_pod.tpl
Labels: bug::normal, type::bug

#45 Update library chart to fix volume mount bug
  charts/wg-easy/Chart.lock
  charts/wg-easy/Chart.yaml
Labels: type::chore

#46 Fix bad dependency url checkin
  charts/wg-easy/Chart.yaml
Labels: bug::normal, type::bug

#47 Update chart lock file
  charts/wg-easy/Chart.lock
Labels: bug::normal, type::bug

#37 Service label selector - Allow specifying multiple apps or override entirely
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_labels.tpl
  charts/replicated-library/templates/lib/_statefulset.tpl
  charts/replicated-library/values.yaml
Labels: type::feature

#51 Update wg-easy for 0.7.0 breaking change
  charts/wg-easy/Chart.lock
  charts/wg-easy/Chart.yaml
  charts/wg-easy/values.yaml
Labels: type::feature

#52 Check if fullNameOverride is null and not just that the key exists
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_names.tpl
Labels: bug::regression, type::bug

#53 Take out the name override on configmaps
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_configmap.tpl
Labels: bug::regression, type::bug

#54 Release 0.7.1
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
Labels: type::chore

#56 Altered volumeClaimTemplate look to fix zero name issue
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_statefulset.tpl
Labels: bug::normal, type::bug

#57 DaemonSet template
  charts/replicated-library/templates/_all.tpl
  charts/replicated-library/templates/lib/_apps.tpl
  charts/replicated-library/templates/lib/_daemonset.tpl
Labels: type::feature

#60 Release 0.8.0
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
Labels: type::chore

#62 Alter helm-docs gen file to values example.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README.md.gotmpl
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/values-example.yaml
  charts/replicated-library/values.yaml
Labels: type::feature

#63 Add license and CoC
  CODE_OF_CONDUCT.md
  LICENSE
Labels: type::chore
