Repository replicatedhq/helm-charts, pull requests merged in 2023-05, with the labels that each got.

#64 more better gitignore
  .gitignore
Labels: type::chore

#61 Switch to using Context instead of global Object variables
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/_all.tpl
  charts/replicated-library/templates/classes/_configmap.tpl
  charts/replicated-library/templates/classes/_ingress.tpl
  charts/replicated-library/templates/classes/_pvc.tpl
  charts/replicated-library/templates/classes/_secret.tpl
  charts/replicated-library/templates/classes/_service.tpl
  charts/replicated-library/templates/lib/_apps.tpl
  charts/replicated-library/templates/lib/_configmap.tpl
  charts/replicated-library/templates/lib/_configmaps.tpl
  charts/replicated-library/templates/lib/_container.tpl
  charts/replicated-library/templates/lib/_daemonset.tpl
  charts/replicated-library/templates/lib/_deployment.tpl
  charts/replicated-library/templates/lib/_ingress.tpl
  charts/replicated-library/templates/lib/_ingresses.tpl
  charts/replicated-library/templates/lib/_labels.tpl
  charts/replicated-library/templates/lib/_names.tpl
  charts/replicated-library/templates/lib/_pod.tpl
  charts/replicated-library/templates/lib/_pod_annotations.tpl
  charts/replicated-library/templates/lib/_probes.tpl
  charts/replicated-library/templates/lib/_pvc.tpl
  charts/replicated-library/templates/lib/_pvcs.tpl
  charts/replicated-library/templates/lib/_secret.tpl
  charts/replicated-library/templates/lib/_secrets.tpl
  charts/replicated-library/templates/lib/_service.tpl
  charts/replicated-library/templates/lib/_serviceaccount.tpl
  charts/replicated-library/templates/lib/_services.tpl
  charts/replicated-library/templates/lib/_statefulset.tpl
Labels: type::feature

#70 Dynamic app reload when active configmaps and secrets change
  charts/replicated-library/Chart.yaml
  charts/replicated-library/FEATURES.md
  charts/replicated-library/README.md
  charts/replicated-library/README.md.gotmpl
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/README_CONFIG.md.gotmpl
  charts/replicated-library/templates/lib/_pod.tpl
  charts/replicated-library/templates/lib/_pod_annotations.tpl
  charts/replicated-library/values-example.yaml
  charts/replicated-library/values.yaml
Labels: type::feature

#72 Fixing bug in ImagePullSecrets and Probes
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_container.tpl
  charts/replicated-library/templates/lib/_pod.tpl
Labels: bug::normal, type::bug

#69 role and rolebinding templates
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/_all.tpl
  charts/replicated-library/templates/lib/_role.tpl
  charts/replicated-library/templates/lib/_rolebinding.tpl
  charts/replicated-library/templates/lib/_rolebindings.tpl
  charts/replicated-library/templates/lib/_roles.tpl
  charts/replicated-library/templates/lib/_serviceaccount.tpl
  charts/replicated-library/templates/lib/_serviceaccounts.tpl
  charts/replicated-library/values-example.yaml
Labels: type::feature

#73 Update README.md
  charts/replicated-library/README.md
  charts/replicated-library/README_CONFIG.md.gotmpl
Labels: type::chore

#75 Fix: Containers/InitContainers
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_container.tpl
  charts/replicated-library/templates/lib/_init_container.tpl
Labels: bug::normal, type::bug

#71 Updated _ingress.tpl to use ingress name as default for .service.name if serviceName or .service.name is not defined.
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_ingress.tpl
Labels: type::feature

#76 Tidy up pod and container whitespace
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_container.tpl
  charts/replicated-library/templates/lib/_pod.tpl
Labels: bug::normal, type::bug

#74 feat(replicated-library): add support bundle spec
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/templates/_all.tpl
  charts/replicated-library/templates/lib/_analyzer.tpl
  charts/replicated-library/templates/lib/_analyzer_templates.tpl
  charts/replicated-library/templates/lib/_analyzers.tpl
  charts/replicated-library/templates/lib/_collector.tpl
  charts/replicated-library/templates/lib/_collectors.tpl
  charts/replicated-library/templates/lib/_support_bundle.tpl
  charts/replicated-library/templates/lib/_troubleshoot.tpl
  charts/replicated-library/templates/lib/troubleshoot/_collector_collectd.tpl
  charts/replicated-library/templates/lib/troubleshoot/_collector_configMap.tpl
  charts/replicated-library/templates/lib/troubleshoot/_collector_copyFromHost.tpl
  charts/replicated-library/templates/lib/troubleshoot/_collector_data.tpl
  charts/replicated-library/templates/lib/troubleshoot/_collector_exec.tpl
  charts/replicated-library/templates/lib/troubleshoot/_collector_general.tpl
  charts/replicated-library/templates/lib/troubleshoot/_collector_logs.tpl
  charts/replicated-library/templates/lib/troubleshoot/_collector_secrets.tpl
  charts/replicated-library/values-example.yaml
  charts/replicated-library/values.yaml
Labels: type::feature

#77 Remove some KOTS collectors from default support-bundle
  charts/replicated-library/values-example.yaml
  charts/replicated-library/values.yaml
Labels: type::chore

#81 Update changelog
  charts/replicated-library/README_CHANGELOG.md.gotmpl
Labels: type::chore

#78 feat(replicated-library): add preflight pre-install hook
  charts/replicated-library/Chart.yaml
  charts/replicated-library/README.md
  charts/replicated-library/README_CHANGELOG.md.gotmpl
  charts/replicated-library/templates/lib/_preflights.tpl
  charts/replicated-library/templates/lib/_troubleshoot.tpl
  charts/replicated-library/values-example.yaml
  charts/wg-easy/Chart.lock
  charts/wg-easy/Chart.yaml
  charts/wg-easy/values.yaml
Labels: type::feature

#82 add troubleshoot to wg-easy
  charts/wg-easy/Chart.yaml
  charts/wg-easy/templates/replicated-library.yaml
  charts/wg-easy/values.yaml
Labels: type::chore

#85 [wg-easy] Fix chart.lock to match Chart.yaml to allow release
  charts/wg-easy/Chart.lock
Labels: type::chore

#88 Add initial README for wg-easy
  charts/wg-easy/README.md
Labels: type::chore

#87 [replicated-library] Add additional information on updating the READE files
  charts/replicated-library/README.md
  charts/replicated-library/README.md.gotmpl
  charts/replicated-library/README_CONFIG.md.gotmpl
Labels: type::chore

#92 Bump wg-easy chart version
  charts/wg-easy/Chart.yaml
Labels: type::chore
